import { create } from 'zustand';

export type ThemeId = 'rose' | 'indigo' | 'amber' | 'mint' | 'aurora' | 'ocean';

export interface ThemeMeta {
  id: ThemeId;
  nameKey: string;
  icon: string;
  preview: { primary: string; container: string; tertiary: string; bg: string };
}

/* ── hex → "R G B" for Tailwind opacity support ──────────── */
function hexToRgb(hex: string): string {
  const h = hex.replace('#', '');
  return `${parseInt(h.slice(0, 2), 16)} ${parseInt(h.slice(2, 4), 16)} ${parseInt(h.slice(4, 6), 16)}`;
}

/* ── Complete MD3-dark palettes for each theme ───────────── */
type Palette = Record<string, string>;

const palettes: Record<ThemeId, Palette> = {
  /* A ─ Rose Pink (current) */
  rose: {
    'primary': '#FFB3B6',
    'on-primary': '#680019',
    'primary-container': '#EF616F',
    'on-primary-container': '#5B0015',
    'primary-fixed': '#FFDADA',
    'primary-fixed-dim': '#FFB3B6',
    'on-primary-fixed': '#40000C',
    'on-primary-fixed-variant': '#8B152B',
    'secondary': '#FFB3B6',
    'on-secondary': '#541F24',
    'secondary-container': '#703439',
    'on-secondary-container': '#F19FA3',
    'secondary-fixed': '#FFDADA',
    'secondary-fixed-dim': '#FFB3B6',
    'on-secondary-fixed': '#390A10',
    'on-secondary-fixed-variant': '#703439',
    'tertiary': '#6CDBA2',
    'on-tertiary': '#003822',
    'tertiary-container': '#2DA46F',
    'on-tertiary-container': '#00311D',
    'tertiary-fixed': '#89F8BD',
    'tertiary-fixed-dim': '#6CDBA2',
    'on-tertiary-fixed': '#002112',
    'on-tertiary-fixed-variant': '#005233',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#131313',
    'on-background': '#E5E2E1',
    'surface': '#131313',
    'on-surface': '#E5E2E1',
    'surface-variant': '#353534',
    'on-surface-variant': '#DFBFBF',
    'surface-dim': '#131313',
    'surface-bright': '#3A3939',
    'surface-tint': '#FFB3B6',
    'surface-container-lowest': '#0E0E0E',
    'surface-container-low': '#1C1B1B',
    'surface-container': '#201F1F',
    'surface-container-high': '#2A2A2A',
    'surface-container-highest': '#353534',
    'outline': '#A68A8A',
    'outline-variant': '#584142',
    'inverse-surface': '#E5E2E1',
    'inverse-on-surface': '#313030',
    'inverse-primary': '#AC2F41',
  },

  /* B ─ Electric Indigo */
  indigo: {
    'primary': '#B8C3FF',
    'on-primary': '#1A2578',
    'primary-container': '#5B6BBF',
    'on-primary-container': '#1A2270',
    'primary-fixed': '#DEE0FF',
    'primary-fixed-dim': '#B8C3FF',
    'on-primary-fixed': '#000F5C',
    'on-primary-fixed-variant': '#3040A0',
    'secondary': '#C3C5DD',
    'on-secondary': '#2C2F42',
    'secondary-container': '#434659',
    'on-secondary-container': '#DFE0F9',
    'secondary-fixed': '#DFE0F9',
    'secondary-fixed-dim': '#C3C5DD',
    'on-secondary-fixed': '#171A2C',
    'on-secondary-fixed-variant': '#434659',
    'tertiary': '#7FDBCA',
    'on-tertiary': '#003731',
    'tertiary-container': '#1B5B52',
    'on-tertiary-container': '#9AF8E5',
    'tertiary-fixed': '#9AF8E5',
    'tertiary-fixed-dim': '#7FDBCA',
    'on-tertiary-fixed': '#00201B',
    'on-tertiary-fixed-variant': '#00493F',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#111318',
    'on-background': '#E2E2E9',
    'surface': '#111318',
    'on-surface': '#E2E2E9',
    'surface-variant': '#44464F',
    'on-surface-variant': '#C5C6D0',
    'surface-dim': '#111318',
    'surface-bright': '#37393F',
    'surface-tint': '#B8C3FF',
    'surface-container-lowest': '#0C0E13',
    'surface-container-low': '#191B22',
    'surface-container': '#1D1F27',
    'surface-container-high': '#282A31',
    'surface-container-highest': '#33343C',
    'outline': '#8F909A',
    'outline-variant': '#44464F',
    'inverse-surface': '#E2E2E9',
    'inverse-on-surface': '#2E3038',
    'inverse-primary': '#3F50A0',
  },

  /* C ─ Amber Gold */
  amber: {
    'primary': '#FFBF6B',
    'on-primary': '#4A2800',
    'primary-container': '#C07A1A',
    'on-primary-container': '#3D2000',
    'primary-fixed': '#FFDDB5',
    'primary-fixed-dim': '#FFBF6B',
    'on-primary-fixed': '#2A1800',
    'on-primary-fixed-variant': '#6B3E00',
    'secondary': '#DDC2A1',
    'on-secondary': '#3E2D16',
    'secondary-container': '#57432B',
    'on-secondary-container': '#FBDEBB',
    'secondary-fixed': '#FBDEBB',
    'secondary-fixed-dim': '#DDC2A1',
    'on-secondary-fixed': '#291904',
    'on-secondary-fixed-variant': '#57432B',
    'tertiary': '#85D8E8',
    'on-tertiary': '#003640',
    'tertiary-container': '#1A5662',
    'on-tertiary-container': '#A2F0FF',
    'tertiary-fixed': '#A2F0FF',
    'tertiary-fixed-dim': '#85D8E8',
    'on-tertiary-fixed': '#001F27',
    'on-tertiary-fixed-variant': '#004450',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#17130E',
    'on-background': '#EDE0D4',
    'surface': '#17130E',
    'on-surface': '#EDE0D4',
    'surface-variant': '#504539',
    'on-surface-variant': '#D4C4B5',
    'surface-dim': '#17130E',
    'surface-bright': '#3E3830',
    'surface-tint': '#FFBF6B',
    'surface-container-lowest': '#110E09',
    'surface-container-low': '#201B14',
    'surface-container': '#231E17',
    'surface-container-high': '#2E2921',
    'surface-container-highest': '#3A342C',
    'outline': '#9E8E7E',
    'outline-variant': '#504539',
    'inverse-surface': '#EDE0D4',
    'inverse-on-surface': '#352F27',
    'inverse-primary': '#8A5500',
  },

  /* D ─ Mint Green */
  mint: {
    'primary': '#7DFFB3',
    'on-primary': '#00391E',
    'primary-container': '#2EAB6E',
    'on-primary-container': '#002E18',
    'primary-fixed': '#9AFCCB',
    'primary-fixed-dim': '#7DFFB3',
    'on-primary-fixed': '#00210F',
    'on-primary-fixed-variant': '#006D3F',
    'secondary': '#B5CCBA',
    'on-secondary': '#213528',
    'secondary-container': '#374B3E',
    'on-secondary-container': '#D1E8D6',
    'secondary-fixed': '#D1E8D6',
    'secondary-fixed-dim': '#B5CCBA',
    'on-secondary-fixed': '#0C2014',
    'on-secondary-fixed-variant': '#374B3E',
    'tertiary': '#C0B3FF',
    'on-tertiary': '#2B0F6E',
    'tertiary-container': '#433386',
    'on-tertiary-container': '#E3DFFF',
    'tertiary-fixed': '#E3DFFF',
    'tertiary-fixed-dim': '#C0B3FF',
    'on-tertiary-fixed': '#170058',
    'on-tertiary-fixed-variant': '#3A2879',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#0E1512',
    'on-background': '#DFE4DD',
    'surface': '#0E1512',
    'on-surface': '#DFE4DD',
    'surface-variant': '#3F4942',
    'on-surface-variant': '#BFC9C0',
    'surface-dim': '#0E1512',
    'surface-bright': '#343B37',
    'surface-tint': '#7DFFB3',
    'surface-container-lowest': '#09100D',
    'surface-container-low': '#161D19',
    'surface-container': '#1A211D',
    'surface-container-high': '#252C28',
    'surface-container-highest': '#303732',
    'outline': '#89938B',
    'outline-variant': '#3F4942',
    'inverse-surface': '#DFE4DD',
    'inverse-on-surface': '#2B322D',
    'inverse-primary': '#008B50',
  },

  /* E ─ Aurora Purple */
  aurora: {
    'primary': '#D0BCFF',
    'on-primary': '#381E72',
    'primary-container': '#7B61C4',
    'on-primary-container': '#33186A',
    'primary-fixed': '#EADDFF',
    'primary-fixed-dim': '#D0BCFF',
    'on-primary-fixed': '#21005D',
    'on-primary-fixed-variant': '#4F378B',
    'secondary': '#CCC2DC',
    'on-secondary': '#332D41',
    'secondary-container': '#4A4458',
    'on-secondary-container': '#E8DEF8',
    'secondary-fixed': '#E8DEF8',
    'secondary-fixed-dim': '#CCC2DC',
    'on-secondary-fixed': '#1D192B',
    'on-secondary-fixed-variant': '#4A4458',
    'tertiary': '#FFB4A8',
    'on-tertiary': '#690100',
    'tertiary-container': '#8C3228',
    'on-tertiary-container': '#FFDAD4',
    'tertiary-fixed': '#FFDAD4',
    'tertiary-fixed-dim': '#FFB4A8',
    'on-tertiary-fixed': '#3B0906',
    'on-tertiary-fixed-variant': '#73231B',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#141218',
    'on-background': '#E6E0E9',
    'surface': '#141218',
    'on-surface': '#E6E0E9',
    'surface-variant': '#49454F',
    'on-surface-variant': '#CAC4D0',
    'surface-dim': '#141218',
    'surface-bright': '#3B383E',
    'surface-tint': '#D0BCFF',
    'surface-container-lowest': '#0F0D13',
    'surface-container-low': '#1D1A22',
    'surface-container': '#211F27',
    'surface-container-high': '#2B2931',
    'surface-container-highest': '#36343C',
    'outline': '#938F99',
    'outline-variant': '#49454F',
    'inverse-surface': '#E6E0E9',
    'inverse-on-surface': '#322F35',
    'inverse-primary': '#6750A4',
  },

  /* F ─ Ocean Cyan */
  ocean: {
    'primary': '#80D8FF',
    'on-primary': '#003548',
    'primary-container': '#2196B8',
    'on-primary-container': '#002D3E',
    'primary-fixed': '#BDE9FF',
    'primary-fixed-dim': '#80D8FF',
    'on-primary-fixed': '#001F2D',
    'on-primary-fixed-variant': '#004D68',
    'secondary': '#B4CAD6',
    'on-secondary': '#1F333C',
    'secondary-container': '#364954',
    'on-secondary-container': '#D0E6F3',
    'secondary-fixed': '#D0E6F3',
    'secondary-fixed-dim': '#B4CAD6',
    'on-secondary-fixed': '#0A1E27',
    'on-secondary-fixed-variant': '#364954',
    'tertiary': '#FFD180',
    'on-tertiary': '#4A3000',
    'tertiary-container': '#6B4A00',
    'on-tertiary-container': '#FFDFB1',
    'tertiary-fixed': '#FFDFB1',
    'tertiary-fixed-dim': '#FFD180',
    'on-tertiary-fixed': '#2C1A00',
    'on-tertiary-fixed-variant': '#5A3D00',
    'error': '#FFB4AB',
    'on-error': '#690005',
    'error-container': '#93000A',
    'on-error-container': '#FFDAD6',
    'background': '#0E1415',
    'on-background': '#DCE4E5',
    'surface': '#0E1415',
    'on-surface': '#DCE4E5',
    'surface-variant': '#3F484B',
    'on-surface-variant': '#BFC8CB',
    'surface-dim': '#0E1415',
    'surface-bright': '#343D3E',
    'surface-tint': '#80D8FF',
    'surface-container-lowest': '#090F10',
    'surface-container-low': '#161C1E',
    'surface-container': '#1A2122',
    'surface-container-high': '#252B2D',
    'surface-container-highest': '#303738',
    'outline': '#899395',
    'outline-variant': '#3F484B',
    'inverse-surface': '#DCE4E5',
    'inverse-on-surface': '#2B3233',
    'inverse-primary': '#006B8A',
  },
};

/* ── Theme metadata for the UI picker ────────────────────── */
export const themeMetas: ThemeMeta[] = [
  { id: 'rose',   nameKey: 'theme_rose',   icon: '🌹', preview: { primary: '#FFB3B6', container: '#EF616F', tertiary: '#6CDBA2', bg: '#131313' } },
  { id: 'indigo', nameKey: 'theme_indigo', icon: '⚡', preview: { primary: '#B8C3FF', container: '#5B6BBF', tertiary: '#7FDBCA', bg: '#111318' } },
  { id: 'amber',  nameKey: 'theme_amber',  icon: '🍯', preview: { primary: '#FFBF6B', container: '#C07A1A', tertiary: '#85D8E8', bg: '#17130E' } },
  { id: 'mint',   nameKey: 'theme_mint',   icon: '🌿', preview: { primary: '#7DFFB3', container: '#2EAB6E', tertiary: '#C0B3FF', bg: '#0E1512' } },
  { id: 'aurora', nameKey: 'theme_aurora', icon: '🔮', preview: { primary: '#D0BCFF', container: '#7B61C4', tertiary: '#FFB4A8', bg: '#141218' } },
  { id: 'ocean',  nameKey: 'theme_ocean',  icon: '🌊', preview: { primary: '#80D8FF', container: '#2196B8', tertiary: '#FFD180', bg: '#0E1415' } },
];

/* ── Apply CSS custom properties to :root ────────────────── */
function applyTheme(id: ThemeId) {
  const palette = palettes[id];
  if (!palette) return;
  const root = document.documentElement;
  for (const [token, hex] of Object.entries(palette)) {
    root.style.setProperty(`--md-${token}`, hexToRgb(hex));
  }
}

/* ── Zustand store ───────────────────────────────────────── */
const STORAGE_KEY = 'beaverkit_theme';

interface ThemeState {
  themeId: ThemeId;
  setTheme: (id: ThemeId) => void;
}

export const useThemeStore = create<ThemeState>((set) => ({
  themeId: (localStorage.getItem(STORAGE_KEY) as ThemeId) || 'rose',
  setTheme: (id: ThemeId) => {
    localStorage.setItem(STORAGE_KEY, id);
    applyTheme(id);
    set({ themeId: id });
  },
}));

/* ── Bootstrap: apply saved theme on load ────────────────── */
applyTheme(useThemeStore.getState().themeId);
